SRCFILES	:=	main.c \

NAME		:=	philosophers

CC			:=	gcc
CFLAGS		:=	-Wall -Wextra -Werror -g -fsanitize=address 
RM			:=	rm -rf

all			:	
$(NAME)		:	
clean		:	
fclean		:
re			:	fclean all

files		:	
	@touch philo.h main.c philosophers.c

.PHONY		:	all clean fclean re